<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class QuestionRequest extends FormRequest{

    /**
     * Enable authorization for question related requests (Create, Update and Delete)
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    //defining the rules
    public function rules()
    {
        return [
            'title' => 'required',
            'body' => 'required',
            'category_id' => 'required'
        ];
    }

    //defining custom messages (without this function, the default error messages for each will field will be generated by Laravel)
    public function messages ()
    {
        return [
            'title.required' => 'The question title is required.',
            'body.required' => 'The question body is required.',
            'category_id.required' => 'The Category ID is required.'
        ];
    }

}

?>
