<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Model\Categories;
use App\Model\Questions;
use App\User;
use Faker\Generator as Faker;

$factory->define(Questions::class, function (Faker $faker) {
    $title = $faker->sentence; // random sentence generated by Laravel
    return [
        'title' => $title,
        'slug'=> str_slug($title),
        'body'=>$faker->text, //random text generated by Laravel

        //retrieving an existing random Category ID. When we seed, we should make sure the Categories will be seeded before the Questions
        'category_id' => function () {
            return Categories::all()->random();
        },

        //retrieving an existing random User ID When we seed, we should make sure the Users will be seeded before the Questions
        'user_id' => function () {
            return User::all()->random();
        }
    ];
});
